#!/bin/bash

cloc plugin lua |
    awk ' \
        BEGIN      { print  "cloc:" } \
        /Language/ { printf " app:   \t%s\t%s\t%s\t%s\n", $2, $3, $4, $5 } \
        /Lua/      { printf "  lua   \t%s\t%s\t%s\t%s\n", $2, $3, $4, $5 } \
    '

cloc tests |
    awk ' \
        /Language/ { print  " tests:" } \
        /Lua/      { printf "  lua   \t%s\t%s\t%s\t%s\n", $2, $3, $4, $5 } \
    '
